### PR TITLE
refactor style

### PR DESCRIPTION
**Pull request by dyc3**
- refactor scss variables and add global style
- clean up `Main`
- rename scss variables
- add new gradients

Reorganizes and makes our style sheets a little more consistent.

### CODE REVIEW

**Comment by nick-dimeglio** [comment]
The textbox component on the login route is acting up saying that the parameters of the TextBox are invalid. Says the name does not exist in the types defined for the thing. Am I missing a pull from somewhere or should I just delete these, review the rest, and push?

**Comment by dyc3** [comment]
If CI is passing, it's likely your dev environment acting up. Try reloading your vscode by running `Developer: Reload Window`

**Comment by nick-dimeglio** [comment]
Yeah it seems it was my environment. Odd.

**Review by nick-dimeglio — APPROVED** [review]
I really like that red to orange gradient on the danger button. Otherwise, all the variable changes are fine and make it a bit more organized. Seems friendly to work with and makes sense. I'm good with all of these.

**Pull request merged**
