### PR TITLE
Button group component

### PR DESCRIPTION
**Pull request by nick-dimeglio**
All details in commit, but essentially the issue here is that I am completely unsure of how to handle checking if one button is toggled and disabling the others in a button group. I thought initially to use event dispatchers and just let it bubble up to the group component, but slots cannot have directives according to svelte so I do not know which way to take this.

### CODE REVIEW

**Comment by nick-dimeglio** [comment]
This will not pass the tests because it just doesn't work as it is and showcases the issue I was talking about. In that case, I didn't bother formatting it yet.

**Comment by dyc3** [comment]
I was able to get it functional. See the component demo page. Using slots is possible, headless ui was able to do it somehow, but the way they were doing it is way too complicated for my taste so I didn't bother.

A couple more notes:
- maybe we should forego wrapping the buttons in a div, and just let the user handle the container themselves. that way we could have a little more control over how the buttons are rendered on a case-by-case basis, rather than adding a bunch of complexity in `ButtonGroup` to try and handle every use case we want.
- Not sure why there's conflicts, but if you remove your changes in those files it'll be fine.

**Comment by nick-dimeglio** [comment]
Yeah your logic works nicely. I was butchering the explanation on discord, but this is what I meant by passing an array of buttons and mapping each to the render. I was explaining it in a very React way lol. I think this is the only way to make the ButtonGroup as its own component work.

To address the needless complexity issue, we can either keep what we got right now as a tab system and just handle the rest as it comes. I don't foresee many use-cases for the ButtonGroup besides tabs, since most Button components will be placed manually.

Just let me know what to handle next or if you want anything else flushed out on these buttongroups.

**Comment by nick-dimeglio** [comment]
If you think it's good to go, since I think it functions perfectly fine as is, I can try to apply it to the login page using Svelte to basically create the tabs via an if else on whats rendered. I can also style this way as well.

**Comment by dyc3** [comment]
This is your task, you decide when its ready to review. Right now it's still a draft.

**Comment by nick-dimeglio** [comment]
Made a few decent changes to the buttongroup and how I plan to apply it. I made it optional to "forceSelection" which allows you to make the user always have a button selected in the case of the login/register but also allows for people to unselect in the case of questions like multiple choice.

I am having issues thinking of how to handle stopping people from unselecting buttons when trying to force it, so if possible take a look at what I did in the component and let me know if you have any suggestions.

**Comment by dyc3** [comment]
The issue you're having is being caused by Button calling `toggle()` when clicked.

**Review by dyc3 — APPROVED** [review]

**Pull request merged**
